### PR TITLE
Adding Login Page

### PR DESCRIPTION
**Pull request by CatherineNjenga**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Uchechukwu10 — APPROVED** [review]
Good work.

**Comment by Uchechukwu10** [comment]
@hokagedemehin Please confirm this review. Thanks.

**Comment by hokagedemehin** [comment]
There is a folder for only front end work. You should have pushed your work to that folder. Please do so next time so as not to cause confusion in the main repo

**Comment by hokagedemehin** [comment]
@Uchechukwu10 you have already merged the work. Please always check to make sure that the PR follows the guidelines we have set so as to avoid any problems with the backend folks

**Pull request merged**
