### PR TITLE
uploading of the hifi hompage(uncompleted yet)

### PR DESCRIPTION
**Pull request by Olokoburnfire**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.
- [ ] This change requires a documentation update
- [ ] created the hifi hompage file
# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Olokoburnfire** [comment]
The slider of the **WHAT SCHOOLS THINK ABOUT US** section is not functional, 
@hokagedemehin I'm putting this here to remind you

**Comment by hokagedemehin** [comment]
Have you done the header color. I have places the header component in the home component

**Review by hokagedemehin — CHANGES_REQUESTED** [review]
Please resolve the merge conflicts so that I can review your work locally

**Comment by Olokoburnfire** [comment]
> Have you done the header color. I have places the header component in the home component

I just saw it not quite long, il get back to you soon boss

**Comment by Olokoburnfire** [comment]
> Please resolve the merge conflicts so that I can review your work locally

Alright boss, I'll have to watch the video on the readme file then

**Comment by Olokoburnfire** [comment]
> Please resolve the merge conflicts so that I can review your work locally

I resolved the merge conf

**Comment by Olokoburnfire** [comment]
> Please resolve the merge conflicts so that I can review your work locally

Merge Conflict Resolved sir

**Pull request closed without merging**
