### PR TITLE
Added the homepage of the website

### PR DESCRIPTION
**Pull request by Olokoburnfire**
# Description

The homepage of the web app

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by hokagedemehin** [comment]
Hi @Olokoburnfire 

I believe we agreed to remove bootstrap from the project because it is clashing with some of the styles of tailwindcss

Please if you can, you can make another PR where you convert your styles to vanilla css

**Review by hokagedemehin — APPROVED** [review]
Merging this PR now

**Review by Uchechukwu10 — CHANGES_REQUESTED** [review]
Fantastic job done. A few changes are required though to avoid clashing with others codes.

1. The bootstrap utility styling conflicts with that of tailwind so you have an option of using tailwindcss or using pure css styling.
2. In your `home.css` file, avoid styling with elements and ids. Use classes to style all your elements. 

Looking forward to these changes. @Olokoburnfire @ricaNga

**Comment by Olokoburnfire** [comment]
> 

Oh, I'm sorry I'll make the necessary changes today

**Pull request merged**
